import React, {useState, useEffect} from 'react'

export function Dialog() {
    const [count, setCount] = useState(0);
    const [dialog, setDialog] = useState("");
    const [dialog2, setDialog2] = useState("");

    let phrase1 = "Greetings human. Welcome to my memory-card game inspired by the Warhammer 40k universe. The art was generated by Midjourney's AI. Instructions: Don't click on the same card twice."


    function phraseSequence() {

        setTimeout(() => {

            if(count < phrase1.length){
                setDialog(dialog + phrase1[count])
                setCount(count + 1)
            }else {
             clearTimeout()
            }
            }
            , 65);

        
    }

    phraseSequence()
    
    return(
        <div className="dialogBox"><h4>{dialog}<br></br>{dialog2}</h4></div>
    )
}
