import React, {useState, useEffect} from 'react'

export function Dialog({gameover, gameover2}) {
    const [count, setCount] = useState(0);
    const [count2, setCount2] = useState(0);
    const [count3, setCount3] = useState(0);
    const [countGameOver, setCoutGameOver] = useState(0);
    const [gameoverPhrase, setGameover] = useState("Game over, try again. ");
    const [victoryPhrase, setVictory] = useState("Congratulations.          You've achieved victory       .       .        .                        this time.");
    const [dialog, setDialog] = useState(" ");
    const [dialog2, setDialog2] = useState("");
    const [dialog3, setDialog3] = useState("");

    
    let phrase1 = "Greetings human. Welcome to my memory-card game inspired by the Warhammer 40k universe. The art was generated by Midjourney's AI. Instructions: Don't click on the same card twice."
    console.log("Dialog Children Render")

    useEffect(() => {
        const phraseSequence = () => {
            if(gameover === false && dialog !== "") {
                setTimeout(() => {
    
                    if(count < phrase1.length){
                        setDialog(dialog + phrase1[count])
                        setCount(count + 1)
                    } else {
                     clearTimeout()
                     
                    }
                    }
                    , 35);
            } 
            else if(gameover === undefined) {
                setTimeout(() => {   
                    setDialog2("")
                    setDialog("")
                    
                    if(count3 < victoryPhrase.length){
                        setDialog3(dialog3 + victoryPhrase[count3])
                        setCount3(count3 + 1)
                    } else {

                  
                     clearTimeout()
                    }; 
                    }
                    , 35);

            } else {
               
                    setTimeout(() => {
                        setDialog("")
                        setDialog3("")
                        setCount3(0)
                        
                        if(count2 < gameoverPhrase.length){
                            setDialog2(dialog2 + gameoverPhrase[count2])
                            setCount2(count2 + 1)
                        } else {
                            
                            setCoutGameOver(countGameOver + 1)
                            if(countGameOver > 3) {
                                console.log(countGameOver)
                                setDialog2("")
                                setCoutGameOver(0)
                                
                            }
                            
                      
                         clearTimeout()
                        }; 
                        }
                        , 35);
                
    
            }
               
            }

        phraseSequence()

       
        return setCount2(0)
    },[dialog, dialog2, gameover, dialog3])


    return(

        <div className="dialogBox"><h4>{dialog}<br></br>{dialog2} <br></br>{dialog3}</h4></div>
        
    )

    }
